project:
  type: website
  output-dir: docs

website:
  title: "J Crain Consulting"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - articles.qmd

format:
  html:
    # theme: sandstone
    # theme: journal
    theme: yeti
    # theme: quartz
    # backgroundcolor: "#f5e9dd"
    # backgroundcolor: "#FBDEC1"
    backgroundcolor: "#D2F9FC"
    # theme: cosmo
    css: styles.css
    toc: true



