---
title: "About"
---

## Joan K. Crain

30 years of experience in senior leadership roles in trust administration, tax strategies, international wealth planning and family governance at major global financial institutions, including Bank of New York Mellon and Northern Trust

**Education**

- Master of Business Administration, Crummer Graduate School/Rollins College 
- Bachelor of Education, Queens University
- Bachelor of Music, McGill University 

**Certifications**

- CERTIFIED FINANCIAL PLANNER<sup>TM</sup>, issued by Certified Financial Planner Board of Standards

- Trust and Estate Practitioner, issued by The Society of Trust and Estate Practitioners Limited (STEP)

- Accredited Estate Planner (distinguished), issued by National Association of Estate Planners & Councils (NAEPC)

**Awards, Publications and Presentations**

- Hall of Fame inductee, National Association of Estate Planners & Councils

- Hall of Fame inductee and Trust Banker of the Year Award, Florida Bankers Association

- Industry Thought Leader Award, Global Finance Magazine  

- The John C. Myers Award for Scholarship and Leadership, Crummer Graduate School of Business, Rollins College

- The Wall Street Journal Award for  "Outstanding Academic Achievement" (highest GPA), Crummer Graduate School of Business, Rollins College



- Author of multiple articles in professional journals including Trusts & Estates, the American Journal of Family Law, and STEP Journal (international wealth planning). Original contributor to the GCC Governance Code of the Family Business Council-Gulf

- Media featured expert on trusts, estates and family governance, including interviews by global media such as The Wall Street Journal, The New York Times and The Economist, and live on CNBC-Asia television

- Presenter at U.S. and international conferences for groups such as the American Bar Association, the American Institute of Certified Public Accountants, the Hong Kong Chamber of Commerce and community foundations and estate planning councils throughout North America, Asia and the Middle East 
